---
output:
  pdf_document: default
  html_document: default
---

# Overview {#Intro1}

```{r tidyr1, echo = FALSE, message = FALSE, warning = FALSE}

library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=50), tidy = FALSE)

```

**Engaging a transboundary expert network to prioritize coastal and marine habitat management for sea ducks in the Salish Sea**

## Project Summary {#Intro1.1}

Sea ducks are an indicator of ecosystem health in the Salish Sea, which is of global importance to many populations of marine birds that use these transboundary waters throughout the annual cycle. It is therefore imperative to work across management jurisdictions to effectively conserve key areas of habitat for these birds. However, jurisdictional complexities often presents a major challenge to taking an ecosystem scale approach to sea duck management, not least because many information sources (i.e., biological datasets) end at the international border. This work aims to overcome this barrier by harmonizing information in a way that assists agencies responsible for implementing conservation prescriptions.

## Goals {#Intro1.2}

This R user guide aims to fulfill one of the key project initiatives: to identify and assess compatibility of avian datasets in the Salish Sea. By the end of this guide, researchers or resources managers interesting in accessing and compiling the available data resources will know:

(1) Which transboundary data resources are available
(2) Who the data owners are and how to access the data with appropriate permissions
(3) How the datasets are structured, including details on the data collection protocols
(4) What the limitations, challenges, and opportunities are associates with each datasets
(5) How to compile the datasets into a standardize data format

> **WARNING: This guide may not provide all the details needed for the specific analysis you are interested in doing. Data users are responsible for understanding the data collection protocols before proceeding. If in doubt, reach out to the data owner with your questions!**

## Guide Structure

[Chapters 2-8](#BCCWS2) in this guide are dedicated to detailing each dataset separately, and are structure using similar subheadings. The datasets are presented in the following order: Canada, U.S., transboundary. [Chapter 9](#Data) focuses on compiling the data sources into a standardized framework. [Chapter 10](#Dev) is dedicated to modelling frameworks and approaches.

## Acknowledgements {#Intro1.3}

A great deal of time and effort have gone into gathering, compiling, and making the data presented in this guide accessible. Data users need to appropriatly acknowledge the source of the information they are using. This also should including an acknowledgement of volunteer efforts in instances where data were collected by citizen scientist.

This project was a collaborative initiative between Birds Canada, Environment and Climate Change Canada, Ducks Unlimited Canada, Pacific Habitat Join Venture, USGS Cooperative Unit, Washing Department of Fish and Wildlife, and Audubon Washington. Funding for this project was provided by ...

This R User Guide was written by Dr. Danielle Ethier, Population Scientist with Birds Canada. Any comments, edits or suggestions can be sent to [dethier\@birdscanada.org](mailto:dethier@birdscanada.org){.email}. Your feedback is always welcome and appreciated!
